sudo: false
language: java
jdk: oraclejdk8
install:
- gradle clean writePropertiesFile shadowJar javadocArchive sourcesArchive
script:
- gradle build
after_success:
- ! '[[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_REPO_SLUG == ChioriGreene/ChioriWebServer
  ]] && ( [[ $TRAVIS_BRANCH == master ]]
  ) && gradle publish'
env:
  global:
  - TERM=dumb
  - secure: cvSpv9nh1BvdwsYg9eMM7XvGGxh/XLPGg4ZgMfq0a4ccs1CinJA0yN8YMS7lgBjabz40YClQIsHk6B9Afwz6UVd5vfaB9HaaLDTgc4Q+sUoCGOuhsSFSmKK+kUl0bHW0bM6T2rIZ7Fy/dGn5jLV0mj9YdAFgJlaMRCwexoxAWKY=
  - secure: GTjC4bwJqA6vRBSbXrD3GdekfZl/wqo6Oy+fsVI4hGvLywtriGLv8MtX14kGwme/OHtWxkVj7MBxnw+L6uWKvZgjkdNtrPXXSslZlYfwXMQcJOeB7ZgUvp307C+EkfYfBweLiSCU6lXuPOLfRmX1LPJ60kN6jSMk69GlzGvXxnk=
cache:
  directories:
  - $HOME/.gradle/wrapper
  - $HOME/.gradle/native
  - $HOME/.gradle/daemon
  - $HOME/.gradle/caches/jars-1
  - $HOME/.gradle/caches/2.8
